### ISSUE TITLE
require is not defined 

### ISSUE THREAD

**Issue by GajenderTyagi** [bradtraversy/electronshoppinglist#10]
Getting require not defined error 

![image](https://user-images.githubusercontent.com/55408821/73119853-a76b7f00-3f8d-11ea-8df7-237870f9717d.png)

**Comment by GajenderTyagi** [comment]
webPreferences: {
      nodeIntegration: true
    } 

Added the following code when creating a window object and the issue is resolved.

**Comment by alphadead** [comment]
@GajenderTyagi I even tried that but it's still not working

**Comment by GajenderTyagi** [comment]
can you share the repo link ?

**Comment by glebpigulevsky** [comment]
@alphadead https://github.com/bradtraversy/electronshoppinglist/issues/9#issuecomment-917566419

**Comment by alphadead** [comment]
Thanks @glebpigulevsky
