### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sno2** [bradtraversy/electronshoppinglist#7]
I have followed your instructions precisely as shown in your video, yet I always get an error saying-
TypeError: Cannot read property 'on' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! calculator@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the calculator@1.0.0 start script.

I am very confused because it worked yesterday, but won't work today.  I feel like it has something to due with the packages.  Maybe you can't install the same package 2x's?  Please help and thank you for your time!

Index.js File - 

const electron = require('electron');
const path = require('path');
const url = require('url');

const {app, BrowserWindow} = electron;

let mainWin;

// Listen for app to be ready
app.on('ready', function(){
  // Create new window
  mainWin = new BrowserWindow({});

  mainWin.loadURL(url.format({
    pathname: path.join(__dirname, 'app', 'index.html'),
    protocol: 'file:',
    slashes: true
  }));

  mainWin.on('closed', function(){
    app.quit();
  });
});

Package.json File - 

{
  "name": "calculator",
  "version": "1.0.0",
  "description": "Simple Calculator",
  "main": "index.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "Carter Snook",
  "license": "ISC",
  "dependencies": {
    "electron": "^4.1.1"
  }
}

**Comment by demersjd** [comment]
I too get this same error and have followed the directions, and went through them again. I forked his code from here and tried to run it and I get the same error. Has anyone ran into a fix for this?

**Comment by malopolo** [comment]
I fixed it with a simple line :
`npm install --save electron`

Hope it will fix your error :)

**Comment by sno2** [comment]
> I fixed it with a simple line :
> `npm install --save electron`
> 
> Hope it will fix your error :)

lol thanks for bringing me back here ;)  I fixed it with using an older version of electron as the dependencies that I was using were not compatible.  Thanks for the help, though.
